platform :ios, '9.0'
use_frameworks!

target 'AppManager_Example' do
  supports_swift_versions '>= 5.0'
  
  pod 'AppManager', :path => '../'

  target 'AppManager_Tests' do
    inherit! :search_paths
  end
end
